### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zsq4003** [yhan219/navicat_reset_mac#1]
shell脚本的第三行和第四行的两个ID找不到  参考 91F6C435D172C8163E0689D3DAD3F3E9
配置是 M1  版本是  12.2.1

**Comment by yhan219** [comment]
m1没测试过，你进入` ~/Library/Preferences/`目录，找到` com.navicat.NavicatPremium.plist`文件，按一下空格键预览一下，大概如下图这样，看一下最上面两个key值
<img width="852" alt="image" src="https://user-images.githubusercontent.com/12593660/157580134-ba13e613-dfdb-432b-82bf-865128c82131.png">

**Comment by zsq4003** [comment]
感谢，已经解决了。
应该是第一个试用版本用的英文版，key不一样导致的。当前的是中文版的，与你提供的key完全对上了。
