### ISSUE TITLE
为啥我的要重启才生效啊

### ISSUE THREAD

**Issue by maoxikun** [yhan219/navicat_reset_mac#10]
macos12.4+navicat16.0.14中文版，执行命令没出错，注册表和文件也删除成功了

**Comment by hpwin-unti** [comment]
重启能生效就不错了，能白嫖就将就着用吧

**Comment by maoxikun** [comment]
> 

确实，反正电脑不会超过14天不重启，将就着用吧

**Comment by yhan219** [comment]
是不是以前安装过其他破解版或者其他版本。可以**备份数据后备份数据后备份数据后**尝试用`app cleaner`之类的工具完全卸载后再从官网下载最新的试试看

**Comment by maoxikun** [comment]
> 

没有安装过任何破解版本，我系统都是全新安装的，现在将就着用吧，反正没啥影响。
