### ISSUE TITLE
No com.navicat.NavicatPremium.plis

### ISSUE THREAD

**Issue by taofish** [yhan219/navicat_reset_mac#11]
问题： 
我的电脑没有下面这两个文件
~/Library/Preferences/com.navicat.NavicatPremium.plis
~/Library/Application\ Support/PremiumSoft\ CyberTech/Navicat\ CC/Navicat\ Premium/

电脑版本：
<img width="258" alt="image" src="https://user-images.githubusercontent.com/15121642/177161191-e8791bb5-9bae-4f84-9385-85ca1f5b56b0.png">

Navicat版本：Navicat Premium 16

**Comment by yhan219** [comment]
直接运行脚本显示什么

**Comment by taofish** [comment]
<img width="531" alt="截屏2022-07-17 09 18 16" src="https://user-images.githubusercontent.com/15121642/179379949-2083d11e-804c-49b2-8b9d-8a0ba943ffd6.png">
~/Library/Preferences/com.navicat.NavicatPremium.plist ， 任何东西都没有
<img width="530" alt="截屏2022-07-17 09 20 10" src="https://user-images.githubusercontent.com/15121642/179379980-ff716e21-6ee6-4101-a208-8e6379836307.png">
~/Library/Application Support/PremiumSoft CyberTech/Navicat CC/Navicat Premium/ ，也是任何东西都没有

**Comment by yhan219** [comment]
是从官网上下载的最新简体中文版吗

**Comment by taofish** [comment]
直接从app store下载的最新版本 @yhan219

**Comment by yhan219** [comment]
从官网上下载中文版试试看，app store我没试过

**Comment by yhan219** [comment]
有问题重新开启

**Comment by KoRinALL** [comment]
你去使用open -e 打开目录是可以看到的，手动一个一个打开是看不到，查了一下好像是因为权限问题，open命令可以无视这一点
