### ISSUE TITLE
mac m1下没有相关路径

### ISSUE THREAD

**Issue by huangzhuohua** [yhan219/navicat_reset_mac#15]
~/Library/Preferences/com.navicat.NavicatPremium.plis

这个路径在mac m1 /macos12下，没有这个路径

**Comment by yhan219** [comment]
这个是个文件，你到`~/Library/Preferences/`下找找看

**Comment by Dr-Octopus-dev** [comment]
有的，我也是m1 OS12，这个路径末尾少了个t，按tab键试试

**Comment by yhan219** [comment]
有问题重新开启
