### ISSUE TITLE
官网下载的16.1中文版，手动删除key值和隐藏文件无效

### ISSUE THREAD

**Issue by Dr-Octopus-dev** [yhan219/navicat_reset_mac#16]
我的试用期还有3天，手动删除两个key值和隐藏文件后重启，还是剩余3天，是否要等到试用期结束才能重置？

**Comment by yhan219** [comment]
彻底关闭navicat后多试几次

**Comment by Dr-Octopus-dev** [comment]
> 彻底关闭navicat后多试几次

我换了个脚本（[链接](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1669993)，然后尝试了一下成功了，但也不是一次性成功，而是打开plist文件，执行一次脚本发现少了点东西，再执行一次发现又少了点，此时打开Navicat才重置成功

**Comment by yhan219** [comment]
> 

看了下原理应该是一样的，他的更通用点。我这里是写死了两个key直接删除，有可能是你们的key跟我不一样，但是我找了几个同事的电脑试过，都是这两个key。成功就行，哪个好用用哪个
