### ISSUE TITLE
window 版本 navicat premium 16.2.3 重置脚本失效

### ISSUE THREAD

**Issue by thiszwinter** [yhan219/navicat_reset_mac#18]
@echo off

echo Delete HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium\Registration[version and language]
for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\PremiumSoft\NavicatPremium" /s | findstr /L Registration"') do (
    reg delete %%i /va /f
)
echo.

echo Delete Info folder under HKEY_CURRENT_USER\Software\Classes\CLSID
for /f %%i in ('"REG QUERY "HKEY_CURRENT_USER\Software\Classes\CLSID" /s | findstr /E Info"') do (
    reg delete %%i /va /f
)
echo.

echo Finish

pause

**Comment by yhan219** [comment]
这个是mac的重置脚本，windows的github上搜一下，有很多的
