### ISSUE TITLE
请问16.2.9可以使用吗

### ISSUE THREAD

**Issue by Emptyio** [yhan219/navicat_reset_mac#22]

**Comment by pretend-m** [comment]
试了一下不行，不过对照原理我手工改成功了。可以等我写个脚本发布上来

**Comment by Emptyio** [comment]
好的，谢谢
&nbsp;


Empty
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月20日(星期五) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yhan219/navicat_reset_mac] 请问16.2.9可以使用吗 (Issue #22)





 
试了一下不行，不过对照原理我手工改成功了。可以等我写个脚本发布上来

**Comment by pretend-m** [comment]
关于16.2.9的重置试用脚本。我已上传到我的仓库。你可以试试看

**Comment by Emptyio** [comment]
好的 感谢 我试一下
&nbsp;


Empty
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月20日(星期五) 中午11:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yhan219/navicat_reset_mac] 请问16.2.9可以使用吗 (Issue #22)





 
关于16.2.9的重置试用脚本。我已上传到我的仓库。你可以试试看

**Comment by Emptyio** [comment]
> 关于16.2.9的重置脚本。我已上传到我的仓库。你可以试试看

没有看见 有新文件 可以给一下链接吗 谢谢

**Comment by pretend-m** [comment]
有啊，就是reset_navicat.sh
https://github.com/pretend-m/navicat_for_mac_reset

**Comment by Emptyio** [comment]
谢谢 看到了&nbsp;


Empty
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月20日(星期五) 中午11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yhan219/navicat_reset_mac] 请问16.2.9可以使用吗 (Issue #22)





 
有啊，就是reset_navicat.sh
 https://github.com/pretend-m/navicat_for_mac_reset

**Comment by Emptyio** [comment]
可以使用 谢谢！

**Comment by pretend-m** [comment]
> 可以用 谢谢！
能用就行。不客气

**Comment by Emptyio** [comment]
Failed to save password Error code: -25291 
保存密码会出现这个提示，但这个是之前就有的，请问有没有好的办法解决。
可能是由于之前尝试使用破解版导致的，但现在下载安装正版以后依旧存在这个问题
&nbsp;


Empty
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月20日(星期五) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yhan219/navicat_reset_mac] 请问16.2.9可以使用吗 (Issue #22)





  
可以用 谢谢！
 能用就行。不客气

**Comment by pretend-m** [comment]
可以尝试彻底卸载后重新去官网下最新版本。。或者下载一个旧的密码没问题的版本（各大平台上都有），然后在覆盖安装最新版本。

**Comment by yhan219** [comment]
我这里一直有效的，你们的不生效吗？估计跟电脑的型号有关系，我的18款有点老

**Comment by yhan219** [comment]
大兄弟，你这个脚本我可以放到我这里来吗？我注明出处 @Emptyio

**Comment by Emptyio** [comment]
> 大兄弟，你这个脚本我可以放到我这里来吗？我注明出处 @Emptyio

这个是@pretend-m的 可能你需要问一下他的意见

**Comment by pretend-m** [comment]
> 大兄弟，你这个剧本我可以把我放到这里吗？我关联出处@Emptyio

可以的。本就是开源的。。。

**Comment by yhan219** [comment]
这个脚本新版本可以用了吗？我这里最开始的脚本一直都可以用，所以也没注意

**Comment by pretend-m** [comment]
> 这个新的脚本版本可以用吗？我这里最开始的脚本一直都可以用，所以也没注意

可用的。我已经测试过最新版本的16.3.0。理论上来说16以后都兼容。。原理就是你发的那个。

**Comment by yhan219** [comment]
好的，感谢
