### ISSUE TITLE
每次运行脚本以后,分组没有了

### ISSUE THREAD

**Issue by summerKK** [yhan219/navicat_reset_mac#23]
我对连接进行了group,比如 online、debug.但是运行完脚本以后分组就没有了.要重新进行分组

**Comment by yhan219** [comment]
用的是哪个脚本 `[reset_navicat_new.sh](https://github.com/yhan219/navicat_reset_mac/blob/main/reset_navicat_new.sh)`?

**Comment by summerKK** [comment]
> 用的是哪个脚本?这个吗 [reset_navicat_new.sh](https://github.com/yhan219/navicat_reset_mac/blob/main/reset_navicat_new.sh) ?

是的

**Comment by yhan219** [comment]
另外的脚本不能重置吗？这个脚本会删了plist文件

**Comment by summerKK** [comment]
> 另外的脚本不能重置吗？这个脚本会删了plist文件

52pojie 的也试过了,那个也会删除group😭.你们的不会吗?

**Comment by yhan219** [comment]
我的不会删除。重置前你先把数据备份一下，备份的时候记得把密码也勾上。另外我看其他issue上有重置失败的，你这边有遇到没

**Comment by summerKK** [comment]
> 我的不会删除。重置前你先把数据备份一下，备份的时候记得把密码也勾上。另外我看其他issue上有重置失败的，你这边有遇到没

抱歉没看到消息.我现在用这个脚本没有重置分组了,现在用起来非常nice.
之前应该是用了52pojie的才导致分组被删除
