### ISSUE TITLE
下载16 navicat premium 直接运行这个提示

### ISSUE THREAD

**Issue by lishipengh2isea** [yhan219/navicat_reset_mac#24]
下载16 navicat premium 直接运行这个提示 ：
lishipeng@lishipengdeMacBook-Pro navicat_reset_mac % ./reset_navicat.sh
rm: "." and ".." may not be removed
请问是不是一定要等到过期时候再执行这个命令呢？不能提前执行呢？

**Comment by yhan219** [comment]
可以提前执行的。都会重置。这个提示不影响，你看下如果不能正常重置，就试试仓库里另外两个脚本
