### ISSUE TITLE
最新版的16.3.4失效了

### ISSUE THREAD

**Issue by liuhao16** [yhan219/navicat_reset_mac#25]
最新版的16.3.4失效了

**Comment by whitexie** [comment]
`com.navicat.NavicatPremium.plist` 变成二进制文件了

**Comment by jiumengs** [comment]
都试了，

**Comment by mhaozz** [comment]
那个plis文件没了

**Comment by yhan219** [comment]
我改天看下，最近有点忙。如果更换了方式，就有点麻烦了

**Comment by ivanon** [comment]
16.3.5验证已失效

**Comment by yhan219** [comment]
我这里是16.3.7，是有效的，你们电脑是哪个型号的，我找同事的试试看

**Comment by yhan219** [comment]
执行脚本前预览一下`~/Library/Preferences/com.navicat.NavicatPremium.plis`文件中key值为`91F6C435D172C8163E0689D3DAD3F3E9`和`B966DBD409B87EF577C9BBF3363E9614` 数据 (按空格键可以预览）看看有没有这两个key，有的话执行完再预览下看看还在不

**Comment by KimiUse** [comment]
我是16.3.7，没有去删除和修改那些文件。第一次先reset_navicat_new.sh，快过期后再次跑reset_navicat_new.sh但是不生效，于是我跑了reset_navicat.sh但是报错了，因为我的com.navicat.NavicatPremium.plis并没有91F6C435D172C8163E0689D3DAD3F3E9和B966DBD409B87EF577C9BBF3363E9614，于是我再次跑reset_navicat_new.sh就成功重置了

**Comment by tangwan** [comment]
> 执行脚本前预览一下`~/Library/Preferences/com.navicat.NavicatPremium.plis`文件中key值为`91F6C435D172C8163E0689D3DAD3F3E9`和`B966DBD409B87EF577C9BBF3363E9614` 数据 (按空格键可以预览）看看有没有这两个key，有的话执行完再预览下看看还在不

16.3.4 执行完`reset_navicat.sh`这俩值还存在，macOS 14.4.1，猜测脚本里面的`defaults delete`可能没生效
![image](https://github.com/yhan219/navicat_reset_mac/assets/15011585/0a8d6212-1afe-4934-a241-af4d6e3d58c2)

**Comment by yhan219** [comment]
可能是新版的mac没有PlistBuddy这个工具了，可以看下`/usr/libexec/PlistBuddy`这个存不存在。如果确实不存在，可以试试`reset_navicat_52pojie.sh`，这个是用`defaults`去删的。如果都不生效，就用`reset_navicat_new.sh`，这个是删除整个plist，执行前记得导出下链接，以免数据丢失。

**Comment by yhan219** [comment]
看看这两个命令有没有
![Uploading image.png…]()

**Comment by tangwan** [comment]
> /usr/libexec/PlistBuddy

这两个命令还是有的

![image](https://github.com/yhan219/navicat_reset_mac/assets/15011585/b9a15907-bf24-47e4-b8c1-4969cccc5e4a)

**Comment by tangwan** [comment]
> 可能是新版的mac没有PlistBuddy这个工具了，可以看下`/usr/libexec/PlistBuddy`这个存不存在。如果确实不存在，可以试试`reset_navicat_52pojie.sh`，这个是用`defaults`去删的。如果都不生效，就用`reset_navicat_new.sh`，这个是删除整个plist，执行前记得导出下链接，以免数据丢失。

可以了，已经可以打开了。

**Comment by yhan219** [comment]
已支持最新版本17
