### ISSUE TITLE
我这儿好像没生效

### ISSUE THREAD

**Issue by 96XL** [yhan219/navicat_reset_mac#5]
运行脚本，最后提示
rm: "." and ".." may not be removed
![image](https://user-images.githubusercontent.com/41610506/167578001-6f52ee47-6e0c-43e5-9efa-5afb1b6dffdf.png)

**Comment by yhan219** [comment]
不影响，你重启下navicat看看试用期是不是重置为14天了

**Comment by 96XL** [comment]
> 不影响，你重启下navicat看看试用期是不是重置为14天了

我现在剩10天，运行完还是10天。还是说要等试用期过完了才生效？

**Comment by yhan219** [comment]
是中文版的吗

**Comment by shijie-todd** [comment]
我也是一样的问题，看了那两个key是跟脚本一致
<img width="721" alt="截屏2022-05-11 上午11 32 52" src="https://user-images.githubusercontent.com/55285084/167763884-ee7d9d7e-c85e-4cfb-b07d-90d0287a2bb3.png">
的

**Comment by shijie-todd** [comment]
执行完脚本，看preferences/ com.xxx 里这两个key都没了，然后rm -rf没执行成功，手动删除也还是不行

**Comment by yhan219** [comment]
重启了Navicat没有

**Comment by hpwin-unti** [comment]
<img width="816" alt="WX20220511-155053@2x" src="https://user-images.githubusercontent.com/40851247/167797350-766f3c64-4a64-49a1-a3cd-bcd6d9e728c8.png">
原本key是相符的，运行完脚本后key变成了这样，重启后试用天数不变

**Comment by yhan219** [comment]
运行脚本后，进入`~/Library/Application\ Support/PremiumSoft\ CyberTech/Navicat\ CC/Navicat\ Premium/`目录下，看看有没有.开头的隐藏文件，有的话删除试试

**Comment by yhan219** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/12593660/167800041-94cf9eca-6b5f-4f3d-a50b-0be461f1ab51.png">
删除这个

**Comment by 96XL** [comment]
> 按照上面那个看看

我的可以了。
昨天运行完脚本重启navicat后天数没有变化，试了几次都不行。
然后我把它设置为了定时脚本，早上九点执行，然后去忙别的了就没管。
今天来了之后打开navicat之后发现天数被重置了，不清楚为什么会这样。

**Comment by hpwin-unti** [comment]
> 运行脚本后，进入`~/Library/Application\ Support/PremiumSoft\ CyberTech/Navicat\ CC/Navicat\ Premium/`目录下，看看有没有.开头的隐藏文件，有的话删除试试

该目录下没有隐藏文件，上述的目录地址就是.AC9E24....的地址吗

**Comment by shijie-todd** [comment]
执行脚本前
<img width="1318" alt="截屏2022-05-12 下午3 09 19" src="https://user-images.githubusercontent.com/55285084/168013435-6d8d4656-cf4d-415c-8b59-a27fe919f77b.png">
执行脚本后
<img width="1361" alt="截屏2022-05-12 下午3 12 14" src="https://user-images.githubusercontent.com/55285084/168013465-6f0fcac0-44e8-4675-8d97-960115052e2f.png">
重启 
<img width="530" alt="截屏2022-05-12 下午3 13 08" src="https://user-images.githubusercontent.com/55285084/168013492-3749513c-9f51-4603-8d7e-11538639f35d.png">

**Comment by yhan219** [comment]
> > 运行脚本后，进入`~/Library/Application\ Support/PremiumSoft\ CyberTech/Navicat\ CC/Navicat\ Premium/`目录下，看看有没有.开头的隐藏文件，有的话删除试试
> 
> 该目录下没有隐藏文件，上述的目录地址就是.AC9E24....的地址吗

每个人的隐藏文件不一样，把所有点开头的文件删了就行了

**Comment by yhan219** [comment]
> 执行脚本前 <img alt="截屏2022-05-12 下午3 09 19" width="1318" src="https://user-images.githubusercontent.com/55285084/168013435-6d8d4656-cf4d-415c-8b59-a27fe919f77b.png"> 执行脚本后 <img alt="截屏2022-05-12 下午3 12 14" width="1361" src="https://user-images.githubusercontent.com/55285084/168013465-6f0fcac0-44e8-4675-8d97-960115052e2f.png"> 重启 <img alt="截屏2022-05-12 下午3 13 08" width="530" src="https://user-images.githubusercontent.com/55285084/168013492-3749513c-9f51-4603-8d7e-11538639f35d.png">

看截图好像`~/Library/Application\ Support/PremiumSoft\ CyberTech/Navicat\ CC/Navicat\ Premium/`目录下的`info.plist`文件都被删了，按理说是不会删除的，只会删除点开头的隐藏文件。我的执行前和执行后，目录下的文件如图
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/12593660/168092188-b2720ecd-7935-4427-a911-f5e008b660db.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/12593660/168092317-7ce5fb35-b1cd-4e4f-948b-d1335869bbcb.png">

**Comment by yhan219** [comment]
原理其实就是这个，
https://github.com/yhan219/navicat_reset_mac#%E5%8E%9F%E7%90%86%E8%AF%B4%E6%98%8E，你们对照了看一下

**Comment by yhan219** [comment]
navicat要退出，不是关闭，点了navicat的x号默认是关闭

**Comment by shijie-todd** [comment]
重启了下mac，再执行脚本就成功了，感谢🙏

**Comment by hpwin-unti** [comment]
电脑重启后成功了，谢谢各位
