### ISSUE TITLE
Mac M1 每次执行脚本后都需要重启才生效吗？

### ISSUE THREAD

**Issue by dubaoquan404** [yhan219/navicat_reset_mac#9]
Macbook M1 每次执行脚本后需要手动重启电脑才生效，目前没办法通过定时任务执行脚本重置了

**Comment by yhan219** [comment]
M1不太清楚，目前我的电脑只要重启应用就可以生效了，不用重启电脑。你运行脚本后试试退出应用再打开，注意是退出，不是点×

**Comment by dubaoquan404** [comment]
> M1不太清楚，目前我的电脑只要重启应用就可以生效了，不用重启电脑。你运行脚本后试试退出应用再打开，注意是退出，不是点×关闭

是的，肯定是完全退出应用了，我的M1 需要重启才生效，另一台intel版本的Mac 不需要重启 定时任务好用，实在不知道M1为什么这样
